### ISSUE TITLE
Issue with HA 0.110.0

### ISSUE THREAD

**Issue by sparment** [iantrich/restriction-card#32]
Since updating to HA 0.110.0 attempting to open a Lovelace card using Restriction Card crashes my system.

**Comment by iantrich** [comment]
config

**Comment by sparment** [comment]
Sorry, this is the first GitHub issue I’ve ever raised and I’m not sure what you are asking me. I’m running Restriction Card 1.3.8

**Comment by iantrich** [comment]
the config of your card

**Comment by sparment** [comment]
cards:
      - type: custom:restriction-card
        restrictions:
          pin:
            code: !secret alarm_pin
            text: "Enter Alarm Pin"
        card:
          type: alarm-panel
          entity: alarm_control_panel.abode_alarm
        title: Alarm
        show_header_toggle: false

**Comment by iantrich** [comment]
Any browser console logs?

**Comment by iantrich** [comment]
oh are you using a stack?

**Comment by sparment** [comment]
Here is the browser console log error:

[Error] hui-error-card – TypeError: s.setConfig is not a function. (In 's.setConfig(e)', 's.setConfig' is undefined) — restriction-card.js:200:6871
TypeError: s.setConfig is not a function. (In 's.setConfig(e)', 's.setConfig' is undefined) — restriction-card.js:200:6871
	s (restriction-card.js:200:6904)
	bt (restriction-card.js:200:7311)
	renderCard (restriction-card.js:218:12721)
	render (restriction-card.js:216:1005)
	update (restriction-card.js:186:1190)
	performUpdate (restriction-card.js:148:7166)
	(anonymous function) (restriction-card.js:148:6861)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise

**Comment by sparment** [comment]
I am using a stack on the tab that is crashing out. On another tab I am not using a stack and when I click on the icon that is linked to a restricted card nothing happens. I get what appears to be the same error as posted above.

**Comment by iantrich** [comment]
It should be fixed in 0.110.2, I believe

**Comment by sparment** [comment]
I’m having the same issue after updating to 0.110.2. Any help would be appreciated!

**Comment by iantrich** [comment]
Nothing to do with the card, it's a core issue.

**Comment by sparment** [comment]
Yes, I cleared the cache. Is this a wide spread issue impacting the Restriction Card?

**Comment by sparment** [comment]
@iantrich any thoughts on this issue? I have seen similar problems posted regarding other custom cards and the developers have made changes to address the errors. Any help would be appreciated!

**Comment by iantrich** [comment]
I'll take a look sometime this week

**Comment by sparment** [comment]
Thanks

**Comment by tech165** [comment]
@sparment do you have any other examples of custom cards with this problem ? I have the same problem here and maybe if I saw what the others did to fix I could help. Thanks

**Comment by sparment** [comment]
I’m not having any issues other than with the restriction card, but I saw it mentioned on another GitHub site the other day... I can’t remember which one though.

**Comment by tech165** [comment]
This is my config : 

      - entities:
          - card:
              entity: cover.porte_garage_maison
              name: Porte Garage Maison
            condition:
              entity: cover.porte_garage_maison
              value: closed
            restrictions:
              confirm:
                text: Êtes-vous sûr de vouloir débarrer ce contrôle ?
            row: true
            type: 'custom:restriction-card'
        show_header_toggle: false
        title: Portes Garages
        type: entities

It does'nt change if I remove then conditions ... I have other restrictions cards with switch that works good. I'm wondering if it has to do with the lazy loading that was introduced in 107 because cover are lazy loaded and not switches ... the alarm-panel panel is also lazy loaded ....

**Comment by sparment** [comment]
I was wondering about the changes in 107 and well. I have the preloader Lovelace plugin installed and preload the alarm-panel card. What's weird is sometimes it works and sometimes it crashes the web browser. I can't figure out why it works intermittently.
I updated the config since my initial post and following the preloader:

    cards:
      - type: entities
        entities:
          - type: 'custom:restriction-card'
            restrictions:
              pin:
                code: !secret alarm_pin
                text: "Enter Alarm PIN"
            card:
              type: 'custom:hui-alarm-panel-card'
              entity: alarm_control_panel.abode_alarm
            row: true

**Comment by sparment** [comment]
@iantrich any luck looking into this? Thanks

**Comment by sparment** [comment]
It looks like if I first activate another custom card (like browser-mod) and then access a restriction card it works. I have to do this each time a page is loaded though...

**Comment by iantrich** [comment]
Should be fixed in 1.2.0

**Comment by sparment** [comment]
Worked for me - thank you!

**Comment by tech165** [comment]
For me too ! Thanks a lot !
